In [1]:
import pandas as pd
import numpy as np 
import requests

df = pd.read_json('../data/auto.json',
                  orient='records')

In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [3]:
df.sample(
    n = 200,
    random_state = 21,
    replace = True
         )

        CarNumber  Refund    Fines        Make   Model
207  Y351O8197RUS       1  1500.00        Ford   Focus
48    H917TC36RUS       2  4000.00        Ford   Focus
368  C589EY154RUS       1  4500.00        Ford   Focus
120   K846YE77RUS       2  2000.00  Volkswagen  Passat
419  X4108H125RUS       2  1300.00        Ford   Focus
..            ...     ...      ...         ...     ...
587  M942OT152RUS       1  2000.00        Ford   Focus
595  Y187O8161RUS       2   400.00        Ford   Focus
365  7064C8197RUS       1 12800.00  Volkswagen  Passat
474  8437XX154RUS       2   800.00        Ford   Focus
592   C410X938RUS       2  2200.00        Ford   Focus

[200 rows x 5 columns]

In [4]:
sample = df.sample(
    n=200,
    random_state=21,
    replace=True
)

In [5]:
concat_rows = pd.concat([df,sample],ignore_index = True)

In [6]:
len(df)-len(concat_rows)

-200

In [7]:
np.random.seed(21)
Year = np.random.randint(1980, 2020, size = len(concat_rows))

In [8]:
Year = pd.Series(Year, name = 'Year')

In [9]:
concat_rows = pd.concat([concat_rows,Year], axis =1)

In [10]:
concat_rows.head()

      CarNumber  Refund   Fines    Make  Model  Year
0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
2   7184TT36RUS       1 2100.00    Ford  Focus  1984
3  X582HE161RUS       2 2000.00    Ford  Focus  2015
4  92918M178RUS       1 5700.00    Ford  Focus  2014

In [11]:
unique_numbers = concat_rows['CarNumber'].unique()
len(unique_numbers)

531

In [12]:
surnames = pd.read_json('../data/surname.json')
surnames.columns = surnames.iloc[0]
surnames = surnames.iloc[1:].reset_index(drop=True)

In [13]:
name_series = surnames['NAME']

In [14]:
surname_sample = name_series.sample(n = len(unique_numbers), random_state = 21, replace = True)

In [15]:
owners = pd.DataFrame({
    'CarNumber': unique_numbers,
    'SURNAME': surname_sample.values
})

In [16]:
owners.head()

      CarNumber     SURNAME
0  Y163O8161RUS  RICHARDSON
1   E432XX77RUS        ROSS
2   7184TT36RUS      MORGAN
3  X582HE161RUS      BAILEY
4  92918M178RUS       LOPEZ

In [17]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  "import pandas as pd\nimport numpy as np \nimport requests\n\ndf = pd.read_json('../data/auto.json',\n                  orient='records')",
  "pd.options.display.float_format = '{:.2f}'.format",
  'df.sample(\n    n = 200,\n    random_state = 21,\n    replace = True\n         )',
  'sample = df.sample(\n    n=200,\n    random_state=21,\n    replace=True\n)',
  'concat_rows = pd.concat([df,sample],ignore_index = True)',
  'len(df)-len(concat_rows)',
  'np.random.seed(21)\nYear = np.random.randint(1980, 2020, size = len(concat_rows))',
  "Year = pd.Series(Year, name = 'Year')",
  'concat_rows = pd.concat([concat_rows,Year], axis =1)',
  'concat_rows.head()',
  "unique_numbers = concat_rows['CarNumber'].unique()\nlen(unique_numbers)",
  "surnames = pd.read_json('../data/surname.json')\nsurnames.columns = surnames.iloc[0]\nsurnames = surnames.iloc[1:].reset_index(drop=True)",
  "name_series = surnames['NAME']",
  'surname_sample = name_series.sample(n = len(unique_numbers), random_state = 21, replace = True)',
  "owners = pd.DataFrame({\n    'CarNumber': unique_numbers,\n    'SURNAME': surname_sample.values\n})",
  'owners.head()',
  'locals()'],
 '_oh': {3:         CarNumber  Refund    Fines        Make   Model
  207  Y351O8197RUS       1  1500.00        Ford   Focus
  48    H917TC36RUS       2  4000.00        Ford   Focus
  368  C589EY154RUS       1  4500.00        Ford   Focus
  120   K846YE77RUS       2  2000.00  Volkswagen  Passat
  419  X4108H125RUS       2  1300.00        Ford   Focus
  ..            ...     ...      ...         ...     ...
  587  M942OT152RUS       1  2000.00        Ford   Focus
  595  Y187O8161RUS       2   400.00        Ford   Focus
  365  7064C8197RUS       1 12800.00  Volkswagen  Passat
  474  8437XX154RUS       2   800.00        Ford   Focus
  592   C410X938RUS       2  2200.00        Ford   Focus

  [200 rows x 5 columns],
  6: -200,
  10:       CarNumber  Refund   Fines    Make  Model  Year
  0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
  1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
  2   7184TT36RUS       1 2100.00    Ford  Focus  1984
  3  X582HE161RUS       2 2000.00    Ford  Focus  2015
  4  92918M178RUS       1 5700.00    Ford  Focus  2014,
  11: 531,
  16:       CarNumber     SURNAME
  0  Y163O8161RUS  RICHARDSON
  1   E432XX77RUS        ROSS
  2   7184TT36RUS      MORGAN
  3  X582HE161RUS      BAILEY
  4  92918M178RUS       LOPEZ},
 '_dh': [PosixPath('/Users/andrejpolozkov/Documents/School 21/Основа/DS_Bootcamp_Part2/DSB7_Pandas.ID_1577650-1/src/ex04')],
 'In': ['',
  "import pandas as pd\nimport numpy as np \nimport requests\n\ndf = pd.read_json('../data/auto.json',\n                  orient='records')",
  "pd.options.display.float_format = '{:.2f}'.format",
  'df.sample(\n    n = 200,\n    random_state = 21,\n    replace = True\n         )',
  'sample = df.sample(\n    n=200,\n    random_state=21,\n    replace=True\n)',
  'concat_rows = pd.concat([df,sample],ignore_index = True)',
  'len(df)-len(concat_rows)',
  'np.random.seed(21)\nYear = np.random.randint(1980, 2020, size = len(concat_rows))',
  "Year = pd.Series(Year, name = 'Year')",
  'concat_rows = pd.concat([concat_rows,Year], axis =1)',
  'concat_rows.head()',
  "unique_numbers = concat_rows['CarNumber'].unique()\nlen(unique_numbers)",
  "surnames = pd.read_json('../data/surname.json')\nsurnames.columns = surnames.iloc[0]\nsurnames = surnames.iloc[1:].reset_index(drop=True)",
  "name_series = surnames['NAME']",
  'surname_sample = name_series.sample(n = len(unique_numbers), random_state = 21, replace = True)',
  "owners = pd.DataFrame({\n    'CarNumber': unique_numbers,\n    'SURNAME': surname_sample.values\n})",
  'owners.head()',
  'locals()'],
 'Out': {3:         CarNumber  Refund    Fines        Make   Model
  207  Y351O8197RUS       1  1500.00        Ford   Focus
  48    H917TC36RUS       2  4000.00        Ford   Focus
  368  C589EY154RUS       1  4500.00        Ford   Focus
  120   K846YE77RUS       2  2000.00  Volkswagen  Passat
  419  X4108H125RUS       2  1300.00        Ford   Focus
  ..            ...     ...      ...         ...     ...
  587  M942OT152RUS       1  2000.00        Ford   Focus
  595  Y187O8161RUS       2   400.00        Ford   Focus
  365  7064C8197RUS       1 12800.00  Volkswagen  Passat
  474  8437XX154RUS       2   800.00        Ford   Focus
  592   C410X938RUS       2  2200.00        Ford   Focus

  [200 rows x 5 columns],
  6: -200,
  10:       CarNumber  Refund   Fines    Make  Model  Year
  0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
  1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
  2   7184TT36RUS       1 2100.00    Ford  Focus  1984
  3  X582HE161RUS       2 2000.00    Ford  Focus  2015
  4  92918M178RUS       1 5700.00    Ford  Focus  2014,
  11: 531,
  16:       CarNumber     SURNAME
  0  Y163O8161RUS  RICHARDSON
  1   E432XX77RUS        ROSS
  2   7184TT36RUS      MORGAN
  3  X582HE161RUS      BAILEY
  4  92918M178RUS       LOPEZ},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10ce1aba0>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x10cec1fd0>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x10cec1fd0>,
 'open': <function _io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
 '_':       CarNumber     SURNAME
 0  Y163O8161RUS  RICHARDSON
 1   E432XX77RUS        ROSS
 2   7184TT36RUS      MORGAN
 3  X582HE161RUS      BAILEY
 4  92918M178RUS       LOPEZ,
 '__': 531,
 '___':       CarNumber  Refund   Fines    Make  Model  Year
 0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
 1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
 2   7184TT36RUS       1 2100.00    Ford  Focus  1984
 3  X582HE161RUS       2 2000.00    Ford  Focus  2015
 4  92918M178RUS       1 5700.00    Ford  Focus  2014,
 '__vsc_ipynb_file__': '/Users/andrejpolozkov/Documents/School 21/Основа/DS_Bootcamp_Part2/DSB7_Pandas.ID_1577650-1/src/ex04/enrichment.ipynb',
 '_i': 'owners.head()',
 '_ii': "owners = pd.DataFrame({\n    'CarNumber': unique_numbers,\n    'SURNAME': surname_sample.values\n})",
 '_iii': 'surname_sample = name_series.sample(n = len(unique_numbers), random_state = 21, replace = True)',
 '_i1': "import pandas as pd\nimport numpy as np \nimport requests\n\ndf = pd.read_json('../data/auto.json',\n                  orient='records')",
 'pd': <module 'pandas' from '/Users/andrejpolozkov/Library/Python/3.13/lib/python/site-packages/pandas/__init__.py'>,
 'np': <module 'numpy' from '/Users/andrejpolozkov/Library/Python/3.13/lib/python/site-packages/numpy/__init__.py'>,
 'requests': <module 'requests' from '/Users/andrejpolozkov/Library/Python/3.13/lib/python/site-packages/requests/__init__.py'>,
 'df':         CarNumber  Refund    Fines    Make    Model
 0    Y163O8161RUS       2  3200.00    Ford    Focus
 1     E432XX77RUS       1  6500.00  Toyota    Camry
 2     7184TT36RUS       1  2100.00    Ford    Focus
 3    X582HE161RUS       2  2000.00    Ford    Focus
 4    92918M178RUS       1  5700.00    Ford    Focus
 ..            ...     ...      ...     ...      ...
 720  Y163O8161RUS       2  1600.00    Ford    Focus
 721  M0309X197RUS       1 22300.00    Ford    Focus
 722  O673E8197RUS       2   600.00    Ford    Focus
 723  8610T8154RUS       1  2000.00    Ford    Focus
 724  H419XE197RUS       2  8594.59  Toyota  Corolla

 [725 rows x 5 columns],
 '_i2': "pd.options.display.float_format = '{:.2f}'.format",
 '_i3': 'df.sample(\n    n = 200,\n    random_state = 21,\n    replace = True\n         )',
 '_3':         CarNumber  Refund    Fines        Make   Model
 207  Y351O8197RUS       1  1500.00        Ford   Focus
 48    H917TC36RUS       2  4000.00        Ford   Focus
 368  C589EY154RUS       1  4500.00        Ford   Focus
 120   K846YE77RUS       2  2000.00  Volkswagen  Passat
 419  X4108H125RUS       2  1300.00        Ford   Focus
 ..            ...     ...      ...         ...     ...
 587  M942OT152RUS       1  2000.00        Ford   Focus
 595  Y187O8161RUS       2   400.00        Ford   Focus
 365  7064C8197RUS       1 12800.00  Volkswagen  Passat
 474  8437XX154RUS       2   800.00        Ford   Focus
 592   C410X938RUS       2  2200.00        Ford   Focus

 [200 rows x 5 columns],
 '_i4': 'sample = df.sample(\n    n=200,\n    random_state=21,\n    replace=True\n)',
 'sample':         CarNumber  Refund    Fines        Make   Model
 207  Y351O8197RUS       1  1500.00        Ford   Focus
 48    H917TC36RUS       2  4000.00        Ford   Focus
 368  C589EY154RUS       1  4500.00        Ford   Focus
 120   K846YE77RUS       2  2000.00  Volkswagen  Passat
 419  X4108H125RUS       2  1300.00        Ford   Focus
 ..            ...     ...      ...         ...     ...
 587  M942OT152RUS       1  2000.00        Ford   Focus
 595  Y187O8161RUS       2   400.00        Ford   Focus
 365  7064C8197RUS       1 12800.00  Volkswagen  Passat
 474  8437XX154RUS       2   800.00        Ford   Focus
 592   C410X938RUS       2  2200.00        Ford   Focus

 [200 rows x 5 columns],
 '_i5': 'concat_rows = pd.concat([df,sample],ignore_index = True)',
 'concat_rows':         CarNumber  Refund    Fines        Make   Model  Year
 0    Y163O8161RUS       2  3200.00        Ford   Focus  1989
 1     E432XX77RUS       1  6500.00      Toyota   Camry  1995
 2     7184TT36RUS       1  2100.00        Ford   Focus  1984
 3    X582HE161RUS       2  2000.00        Ford   Focus  2015
 4    92918M178RUS       1  5700.00        Ford   Focus  2014
 ..            ...     ...      ...         ...     ...   ...
 920  M942OT152RUS       1  2000.00        Ford   Focus  1981
 921  Y187O8161RUS       2   400.00        Ford   Focus  1992
 922  7064C8197RUS       1 12800.00  Volkswagen  Passat  2007
 923  8437XX154RUS       2   800.00        Ford   Focus  2005
 924   C410X938RUS       2  2200.00        Ford   Focus  1997

 [925 rows x 6 columns],
 '_i6': 'len(df)-len(concat_rows)',
 '_6': -200,
 '_i7': 'np.random.seed(21)\nYear = np.random.randint(1980, 2020, size = len(concat_rows))',
 'Year': 0      1989
 1      1995
 2      1984
 3      2015
 4      2014
        ...
 920    1981
 921    1992
 922    2007
 923    2005
 924    1997
 Name: Year, Length: 925, dtype: int64,
 '_i8': "Year = pd.Series(Year, name = 'Year')",
 '_i9': 'concat_rows = pd.concat([concat_rows,Year], axis =1)',
 '_i10': 'concat_rows.head()',
 '_10':       CarNumber  Refund   Fines    Make  Model  Year
 0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
 1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
 2   7184TT36RUS       1 2100.00    Ford  Focus  1984
 3  X582HE161RUS       2 2000.00    Ford  Focus  2015
 4  92918M178RUS       1 5700.00    Ford  Focus  2014,
 '_i11': "unique_numbers = concat_rows['CarNumber'].unique()\nlen(unique_numbers)",
 'unique_numbers': array(['Y163O8161RUS', 'E432XX77RUS', '7184TT36RUS', 'X582HE161RUS',
        '92918M178RUS', 'H234YH197RUS', 'E40577152RUS', '707987163RUS',
        'K330T8197RUS', 'X786CO96RUS', 'C477M7161RUS', 'O21997197RUS',
        'M592CH197RUS', '9020YC197RUS', '8182XX154RUS', '7830C8197RUS',
        '7066C8197RUS', 'M298CH161RUS', 'E445TC197RUS', '8440XX154RUS',
        '9371CE154RUS', '9182CE154RUS', '83298C154RUS', 'Y7659C197RUS',
        'C922YE197RUS', '7364C8197RUS', 'M5039X197RUS', '8603T8154RUS',
        '92928M178RUS', 'O672E8197RUS', 'E42277152RUS', 'C903MC161RUS',
        'T7318T163RUS', 'Y7719C197RUS', 'T011MY163RUS', 'H115YO163RUS',
        '73467Y96RUS', 'O134HE197RUS', 'H968HY161RUS', 'Y654E8750RUS',
        'H963HY161RUS', 'H232YH197RUS', '7843C8197RUS', 'X791O796RUS',
        'H958HY161RUS', '708587163RUS', 'Y973O8197RUS', '97977H178RUS',
        'H917TC36RUS', 'Y7709C197RUS', '8513XX154RUS', 'T870X7163RUS',
        '8818C877RUS', 'T395OT197RUS', 'K327T8197RUS', '8311XX154RUS',
        'X423MK197RUS', '96429X178RUS', 'O275O7161RUS', '7789KT197RUS',
        'E28877161RUS', 'T6068M116RUS', '9498KX178RUS', '99209X178RUS',
        'T6449O50RUS', '9683EC178RUS', 'Y353O8197RUS', 'O719MM163RUS',
        'E535MM199RUS', 'Y352O8197RUS', '7788KT197RUS', 'E807HE77RUS',
        'M516CH161RUS', '89587X197RUS', '7781KT197RUS', 'E645TH36RUS',
        'Y302E877RUS', 'M058XE36RUS', '8166XX154RUS', 'M589CH197RUS',
        '9408H7178RUS', 'H387TM197RUS', '8049HT125RUS', '9698MO178RUS',
        '8685HE154RUS', '7177TT36RUS', 'O77997197RUS', 'Y234E877RUS',
        '97987H178RUS', 'X257HE161RUS', 'T399KX197RUS', 'H957HY161RUS',
        'K379HY161RUS', 'T654HT96RUS', '8439XX154RUS', 'Y965EE197RUS',
        'X758HY197RUS', 'M0279X197RUS', 'H224X836RUS', 'E6849O154RUS',
        'O83797197RUS', '9402KK197RUS', '7368C8197RUS', 'H427YH197RUS',
        '9583EY178RUS', 'Y038E877RUS', '9822H8161RUS', '7826C8197RUS',
        'E160YX77RUS', '82337X197RUS', 'X757HY197RUS', 'X765HY197RUS',
        '934497178RUS', 'K2807K154RUS', 'T8008Y125RUS', 'Y960EE197RUS',
        '7840C8197RUS', 'K846YE77RUS', '7827C8197RUS', 'Y655E8750RUS',
        'H003MH197RUS', 'Y7699C197RUS', 'Y8399C197RUS', '9135X938RUS',
        'H385TM197RUS', '9428EX178RUS', 'H837YK197RUS', 'O83597197RUS',
        'E42577152RUS', 'E53277152RUS', 'C476M7161RUS', '9943KK197RUS',
        '8165XX154RUS', 'T476KX197RUS', 'C422X938RUS', 'K328T8197RUS',
        '9466EX178RUS', 'X256HE161RUS', 'Y275O8197RUS', 'H217X836RUS',
        'Y316E877RUS', '8601XX154RUS', 'M741T9152RUS', '9883HX152RUS',
        'Y6829Y50RUS', 'H004MH197RUS', '704987163RUS', 'E316EH197RUS',
        'O22297197RUS', 'O02597197RUS', 'X015HY197RUS', 'T769OT197RUS',
        'Y778EE197RUS', '7829C8197RUS', 'T272HH163RUS', 'T018OX197RUS',
        'Y255E877RUS', '9697MO178RUS', 'T686EO197RUS', 'C590EY154RUS',
        'T941CC96RUS', 'O22397197RUS', 'X242EC197RUS', 'T020OX197RUS',
        'E33577152RUS', 'E773EH197RUS', 'T6428M116RUS', 'Y7129Y50RUS',
        'Y418EX197RUS', 'Y7689C197RUS', 'E52877152RUS', '7369C8197RUS',
        'Y166O8161RUS', '705287163RUS', 'K559KC161RUS', 'M0299X197RUS',
        '84418C154RUS', 'E53488152RUS', '90159H178RUS', 'C798ET50RUS',
        'Y193O8161RUS', '7248C8197RUS', 'K357YE77RUS', 'E0697X152RUS',
        'E40877152RUS', 'Y351O8197RUS', 'Y356O8197RUS', 'O6939X163RUS',
        'Y7649C197RUS', '9935TE152RUS', '704687163RUS', '7197TT36RUS',
        'O143HO197RUS', 'K436MO152RUS', '9938OH154RUS', 'E34877152RUS',
        'E5878M777RUS', '7844C8197RUS', 'C584EY154RUS', 'E28977161RUS',
        'T016OX197RUS', 'H889YK197RUS', '7363C8197RUS', 'T6039O50RUS',
        '7365C8197RUS', 'Y967O8197RUS', 'E816HE77RUS', 'T6329O50RUS',
        'X504X8197RUS', 'M581CH197RUS', 'X523OM161RUS', 'C412X938RUS',
        '7831C8197RUS', '8164XX154RUS', 'T6419O50RUS', 'E822TH36RUS',
        '8437XX154RUS', 'C515X938RUS', '7172TT36RUS', '8436XX154RUS',
        'E79988152RUS', '8180XX154RUS', '84438C154RUS', 'T6309O50RUS',
        'T6129O50RUS', 'K339T8197RUS', 'X782CO96RUS', 'E591HE77RUS',
        '9499KX178RUS', 'Y357O8197RUS', 'Y652O8197RUS', 'X767HY197RUS',
        'H220X836RUS', 'H218X836RUS', 'T913CT197RUS', 'T6439O50RUS',
        '7784KT197RUS', 'X286TC36RUS', 'O752MX161RUS', 'Y7449Y50RUS',
        '92828M178RUS', 'Y650E8750RUS', '8321XX154RUS', '8316XX154RUS',
        'T017OX197RUS', 'H977HY161RUS', 'X522OM161RUS', 'O085E8197RUS',
        '705387163RUS', 'O017KO197RUS', 'X4138H125RUS', '8441XX154RUS',
        'M0269X197RUS', 'T483CT96RUS', 'T940CC96RUS', 'C58078163RUS',
        'O02397197RUS', '8611T8154RUS', '704787163RUS', 'C313MM99RUS',
        'X763HY197RUS', 'M386M9197RUS', '8605T8154RUS', '7147OE161RUS',
        '7361C8197RUS', 'Y359EY197RUS', 'T6559O50RUS', '9469EX178RUS',
        'Y6839Y50RUS', 'H237YH197RUS', 'T948OM96RUS', 'T395KX197RUS',
        'M301CH161RUS', '9496KX178RUS', 'T6319O50RUS', 'H305T8197RUS',
        '8201XX154RUS', 'O64297197RUS', '9523M8178RUS', 'Y273O8197RUS',
        'T6229O50RUS', 'X023HY197RUS', '8226XX154RUS', 'Y038TO197RUS',
        'M0289X197RUS', 'E811HE77RUS', 'X795O796RUS', 'O39997197RUS',
        '97968K152RUS', 'H219X836RUS', 'T6169O50RUS', '94178K154RUS',
        '9467EX178RUS', 'O78097197RUS', 'X5707X161RUS', 'Y232E877RUS',
        'Y388E877RUS', 'X255HE161RUS', 'E552MO152RUS', '97998K152RUS',
        'Y963O8197RUS', 'T477KX197RUS', 'T2639T116RUS', 'O49797197RUS',
        'O68897197RUS', '72457Y96RUS', '7064C8197RUS', 'E948C8152RUS',
        'C514X938RUS', 'C589EY154RUS', 'K899T8197RUS', 'T6418M116RUS',
        '8607XX154RUS', '92778M178RUS', 'T288CT96RUS', '9886HX152RUS',
        'C583EY154RUS', 'C592EY154RUS', 'T6459O50RUS', 'X759HY197RUS',
        '705787163RUS', '92898M178RUS', '9671EC178RUS', 'M302CH161RUS',
        'M578CH197RUS', 'Y207O8161RUS', '96659X178RUS', 'T912CT197RUS',
        '7183TT36RUS', '89557X197RUS', 'Y359O8197RUS', 'K2817K154RUS',
        'Y964O8197RUS', 'H967HY161RUS', 'E394MO152RUS', 'O50699163RUS',
        '9463EX178RUS', 'E53677152RUS', 'K338T8197RUS', 'Y4298M777RUS',
        'Y687HM197RUS', '98037H178RUS', '7828C8197RUS', 'H980HY161RUS',
        'H906YK197RUS', '7199MT197RUS', 'X908XC197RUS', 'T171CC96RUS',
        'X4108H125RUS', 'Y966O8197RUS', 'K2797K154RUS', '7089H8163RUS',
        '7841C8197RUS', '9940KK197RUS', 'H971HY161RUS', 'H844YH197RUS',
        'E33477152RUS', 'Y156E877RUS', 'E396MO152RUS', 'Y969O8197RUS',
        '9028CO161RUS', 'T6249O50RUS', 'E42377152RUS', '9941KK197RUS',
        'M372CH197RUS', 'K040CC197RUS', 'E41577152RUS', '9763HY161RUS',
        'T535ET96RUS', 'H961HY161RUS', 'M2169X197RUS', '8234XX154RUS',
        'O83697197RUS', 'E52677152RUS', '8451M7154RUS', '9589EY178RUS',
        'H907YK197RUS', 'O39897197RUS', 'M3879X197RUS', 'C299K9154RUS',
        '9468EX178RUS', 'M375CH197RUS', 'H982HY161RUS', '8224XX154RUS',
        'Y653E8750RUS', 'K558KC161RUS', 'O058M7161RUS', 'M256OH161RUS',
        'T242H8197RUS', 'K27188138RUS', '96629X178RUS', '9881HX152RUS',
        'T479KX197RUS', 'M680T9152RUS', 'C410X938RUS', 'X762HY197RUS',
        '9470EX178RUS', 'X4128H125RUS', '9762HY161RUS', 'H419XE197RUS',
        '98017H178RUS', 'Y780EE197RUS', 'M580CH197RUS', '9943OH154RUS',
        'Y354O8197RUS', '7065C8197RUS', 'E28777161RUS', 'M701T9152RUS',
        'E577HE77RUS', '92788M178RUS', '9072EM178RUS', '9409H7178RUS',
        'C3829X154RUS', 'T478KX197RUS', 'T119CT96RUS', '708487163RUS',
        'H983HY161RUS', '7842C8197RUS', 'O64097197RUS', 'Y693HM197RUS',
        '96857X197RUS', 'T394KX197RUS', 'O49897197RUS', 'H963X936RUS',
        'T341CC96RUS', '9942KK197RUS', '9141H8178RUS', '7370C8197RUS',
        '9890HX152RUS', 'M268CH197RUS', 'C419X938RUS', 'M0319X197RUS',
        'M577CH197RUS', 'H975HY161RUS', 'X018HY197RUS', 'E33177152RUS',
        '9491H7178RUS', 'M374CH197RUS', '96679X178RUS', '9594HY161RUS',
        '83218C154RUS', '9764HY161RUS', '708187163RUS', 'H908YK197RUS',
        'Y656E8750RUS', '9679EC178RUS', 'C803KE163RUS', 'Y7379Y50RUS',
        'X320MK197RUS', '96907X197RUS', 'H235YH197RUS', '9474EX178RUS',
        'Y8259C197RUS', 'E29577161RUS', 'X761HY197RUS', 'T396KX197RUS',
        'C593EY154RUS', 'Y164O8161RUS', 'M942OT152RUS', 'Y7429Y50RUS',
        'H976HY161RUS', 'Y195O8161RUS', 'O669E8197RUS', 'Y187O8161RUS',
        'K329T8197RUS', '9677MO178RUS', '9939KK197RUS', 'M373CH197RUS',
        '7164YM36RUS', 'O753MX161RUS', 'T6488M116RUS', '98047H178RUS',
        '9488EY178RUS', 'O481OH77RUS', 'K326T8197RUS', 'X796TH96RUS',
        'Y358O8197RUS', 'C420X938RUS', 'Y965O8197RUS', 'Y274O8197RUS',
        'E223YM197RUS', 'Y964EE197RUS', 'T6049O50RUS', 'H259HY161RUS',
        'Y344E877RUS', 'K889HY161RUS', 'H214X836RUS', 'O421OT161RUS',
        '7360C8197RUS', 'Y194O8161RUS', 'T6359O50RUS', 'E29677161RUS',

In [18]:
len(df)

725

In [19]:
len(sample)

200

In [20]:
len(concat_rows)

925

In [21]:
concat_rows.head()

      CarNumber  Refund   Fines    Make  Model  Year
0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
2   7184TT36RUS       1 2100.00    Ford  Focus  1984
3  X582HE161RUS       2 2000.00    Ford  Focus  2015
4  92918M178RUS       1 5700.00    Ford  Focus  2014

In [22]:
len(owners['SURNAME'])

531

In [23]:
len(owners['CarNumber'])

531

In [24]:
fines = concat_rows.copy()

In [25]:
new_fines_rows = pd.DataFrame({
    'CarNumber': ['AAA111', 'BBB222', 'CCC333', 'DDD444', 'EEE555'],
    'Refund': [1, 2, 1, 2, 1],
    'Fines': [1500, 2200, 3100, 1800, 2600],
    'Make': ['Ford', 'Toyota', 'BMW', 'Ford', 'Toyota'],
    'Model': ['Focus', 'Camry', 'X5', 'Focus', 'Corolla'],
    'Year': [2005, 2006, 2007, 2008, 2009]
})

In [26]:
fines = pd.concat([fines, new_fines_rows], ignore_index=True)
len(fines)

930

In [27]:
owners = owners.iloc[:-20]
len(owners)

511

In [28]:
new_owner_rows = pd.DataFrame({
    'CarNumber': ['ZZZ999', 'YYY888', 'XXX777'],
    'SURNAME': ['SMITH', 'JOHNSON', 'BROWN']
})

owners = pd.concat([owners, new_owner_rows], ignore_index=True)

In [29]:
set(fines['CarNumber']) - set(owners['CarNumber'])

{'7194TT36RUS',
 '7367C8197RUS',
 '8325M7154RUS',
 '8610T8154RUS',
 '9137X938RUS',
 '9398MM199RUS',
 '96599X178RUS',
 '98087H178RUS',
 '9938KK197RUS',
 'AAA111',
 'BBB222',
 'CCC333',
 'DDD444',
 'E53477152RUS',
 'EEE555',
 'H966HY161RUS',
 'M0309X197RUS',
 'M6977E152RUS',
 'O136HO197RUS',
 'O22097197RUS',
 'O673E8197RUS',
 'X583HE161RUS',
 'X760HY197RUS',
 'Y192O8161RUS',
 'Y7229Y50RUS'}

In [30]:
set(owners['CarNumber']) - set(fines['CarNumber'])

{'XXX777', 'YYY888', 'ZZZ999'}

In [31]:
inner_join = fines.merge(
    owners,
    on='CarNumber',
    how='inner'
)

In [32]:
len(inner_join)

903

In [33]:
left_join = fines.merge(
    owners,
    on='CarNumber',
    how='left'
)
len(left_join)

930

In [34]:
right_join = fines.merge(
    owners,
    on='CarNumber',
    how='right'
)
len(right_join)

906

In [35]:
outer_join = fines.merge(
    owners,
    on='CarNumber',
    how='outer'
)
len(outer_join)

933

In [36]:
print(len(fines),len(owners),len(inner_join),len(left_join),len(right_join),len(outer_join))

930 514 903 930 906 933

In [37]:
left_join[left_join['SURNAME'].isna()]

        CarNumber  Refund    Fines        Make    Model  Year SURNAME
687  X583HE161RUS       1  3000.00        Ford    Focus  1984     NaN
688   Y7229Y50RUS       2  2500.00        Ford    Focus  1982     NaN
689  M6977E152RUS       1   500.00        Ford    Focus  1996     NaN
691  8325M7154RUS       1  1000.00        Ford    Focus  1987     NaN
692  Y192O8161RUS       2   300.00        Ford    Focus  1999     NaN
694  96599X178RUS       1   500.00        Ford    Focus  1990     NaN
695  X760HY197RUS       1 10100.00        Ford    Focus  2002     NaN
697  H966HY161RUS       1   500.00        Ford    Focus  2013     NaN
698  9938KK197RUS       2 28500.00        Ford    Focus  1993     NaN
699  98087H178RUS       1  8594.59        Ford    Focus  1999     NaN
702  7367C8197RUS       1  6000.00        Ford    Focus  1993     NaN
703   9137X938RUS       1  1600.00        Ford    Focus  1986     NaN
705  9398MM199RUS       1   300.00  Volkswagen   Passat  2010     NaN
708  E53477152RUS       1  7200.00        Ford    Focus  2008     NaN
713   7194TT36RUS       2  2300.00        Ford    Focus  2002     NaN
715  O136HO197RUS       2  7800.00      Toyota  Corolla  1999     NaN
719  O22097197RUS       1 24300.00        Ford    Focus  2017     NaN
721  M0309X197RUS       1 22300.00        Ford    Focus  1998     NaN
722  O673E8197RUS       2   600.00        Ford    Focus  1985     NaN
723  8610T8154RUS       1  2000.00        Ford    Focus  1995     NaN
846  9398MM199RUS       1   300.00  Volkswagen   Passat  2000     NaN
867  9398MM199RUS       1   300.00  Volkswagen   Passat  2013     NaN
925        AAA111       1  1500.00        Ford    Focus  2005     NaN
926        BBB222       2  2200.00      Toyota    Camry  2006     NaN
927        CCC333       1  3100.00         BMW       X5  2007     NaN
928        DDD444       2  1800.00        Ford    Focus  2008     NaN
929        EEE555       1  2600.00      Toyota  Corolla  2009     NaN

In [38]:
right_join[right_join['Fines'].isna()]

    CarNumber  Refund  Fines Make Model  Year  SURNAME
903    ZZZ999     NaN    NaN  NaN   NaN   NaN    SMITH
904    YYY888     NaN    NaN  NaN   NaN   NaN  JOHNSON
905    XXX777     NaN    NaN  NaN   NaN   NaN    BROWN

In [39]:
pivot = fines.pivot_table(
    values='Fines',
    index='Make',
    columns='Year',
    aggfunc='sum'
)
pivot.head()

Year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Make,,,,,,,,,,,,,,,,,,,,,
Audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BMW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3000.00,NaN,NaN,8594.59,NaN,NaN,6500.00,NaN
Ford,62394.59,395589.17,140383.76,63100.00,111294.59,189583.76,88994.59,121900.00,95989.17,124100.00,...,120183.76,86689.17,147100.00,145494.59,158894.59,203694.59,118794.59,272200.00,285194.59,101100.00
Skoda,12494.59,NaN,6900.00,11594.59,1200.00,10294.59,600.00,26700.00,NaN,91400.00,...,3100.00,500.00,500.00,13794.59,1900.00,46394.59,300.00,NaN,156200.00,9500.00
Toyota,18500.00,8594.59,2000.00,7200.00,NaN,NaN,16000.00,8000.00,NaN,26400.00,...,24000.00,8594.59,16094.59,NaN,NaN,NaN,13000.00,10600.00,13000.00,34100.00

In [40]:
fines.to_csv('../data/fines.csv', index=False)
owners.to_csv('../data/owners.csv', index=False)

In [41]:
concat_rows.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        914
Year         925
dtype: int64

In [42]:
fines.count()

CarNumber    930
Refund       930
Fines        930
Make         930
Model        919
Year         930
dtype: int64